=== OpenMath/OMSVN/www/log.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
  targetNamespace="log" elementFormDefault="qualified" xmlns="log">
  
	<xsd:element name="change">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice>
					<xsd:element name="file" type="xsd:string"/>
					<xsd:element name="files"><xsd:complexType>
						<xsd:sequence><xsd:element name="file" type="xsd:string" maxOccurs="unbounded"/></xsd:sequence>
					</xsd:complexType></xsd:element>
				</xsd:choice>
				<xsd:element name="toldat" type="xsd:string"  minOccurs="0"/>
				<xsd:element name="thanksto" type="xsd:string" minOccurs="0"/>
				<xsd:element name="log" type="xsd:string"/>
			</xsd:sequence>
  		<xsd:attribute name="who" type="xsd:IDREF"/>
  		<xsd:attribute name="date" type="xsd:date"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="logs">
		<xsd:complexType><xsd:sequence>
			<xsd:element ref="change" maxOccurs="unbounded"/>
			<xsd:element ref="persons"/>
		</xsd:sequence></xsd:complexType>
	</xsd:element>
	
	<xsd:element name="persons">
		<xsd:complexType><xsd:sequence>
			<xsd:element name="person" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="name"/>
					<xsd:attribute name="email"/>
					<xsd:attribute name="id" type="xsd:ID"/>
				</xsd:complexType></xsd:element>
		</xsd:sequence></xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== OpenMath/OMSVN/www/log.xml
<?xml version="1.0" encoding="utf-8"?>
<logs xmlns="log" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="log log.xsd">

  <change who="polx" date="2006-07-26">
	  <files>
			<file>sts/integer1.sts</file>
	  	<file>sts/linalg2.sts</file>
		</files>
		<toldat>xx-mail-list-urls</toldat>
		<thanksto>Gl√≥ria Casanellas</thanksto>
		<log>Two little sts errors corrected.</log>
	</change>


  <change who="polx" date="2006-08-11">
	  <file>cd/units_ops1.ocd</file>
		<toldat>http://jira.activemath.org/browse/OM-1</toldat>
		<thanksto>William Naylor</thanksto>
		<log> Made the content of this CD sensible... 
		  missing the presentation of formula, just put as prefix for now. </log>
  </change>
  
	
	
	<persons>
		<person id="polx" name="Paul Libbrecht" email="paul@activemath.org"/>
		<person id="bill" name="William Naylor" email="wn@cs.bath.ac.uk"/>
	</persons>
</logs>


<!-- is this format ok with you ?
  are you a person that validates permanently ? -->
